x-mongo-server: &mongo-server
    image: mongo:latest
    expose:
        - "27017"

services:
    # RS 1
    mongo1:
        <<: *mongo-server
        container_name: mongo1
        ports:
            - 27101:27017
        entrypoint:
            [
                "mongod",
                "--replSet",
                "myReplicaSet",
                "--bind_ip",
                "localhost,mongo1",
            ]
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mongo_cluster/data-1:/data/db
    mongo2:
        <<: *mongo-server
        container_name: mongo2
        ports:
            - 27102:27017
        entrypoint:
            [
                "mongod",
                "--replSet",
                "myReplicaSet",
                "--bind_ip",
                "localhost,mongo2",
            ]
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mongo_cluster/data-2:/data/db
    mongo3:
        <<: *mongo-server
        container_name: mongo3
        ports:
            - 27103:27017
        entrypoint:
            [
                "mongod",
                "--replSet",
                "myReplicaSet",
                "--bind_ip",
                "localhost,mongo3",
            ]
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mongo_cluster/data-3:/data/db
    mongo4:
        <<: *mongo-server
        container_name: mongo4
        ports:
            - 27104:27017
        entrypoint:
            [
                "mongod",
                "--replSet",
                "myReplicaSet",
                "--bind_ip",
                "localhost,mongo4",
            ]
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mongo_cluster/data-4:/data/db
    mongo5:
        <<: *mongo-server
        container_name: mongo5
        ports:
            - 27105:27017
        entrypoint:
            [
                "mongod",
                "--replSet",
                "myReplicaSet",
                "--bind_ip",
                "localhost,mongo5",
            ]
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mongo_cluster/data-5:/data/db

    mongosetup:
        <<: *mongo-server
        depends_on:
            - mongo1
            - mongo2
            - mongo3
            - mongo4
            - mongo5
        volumes:
            - ./scripts:/scripts
        restart: "no"
        entrypoint:
            ["mongosh", "--host", "mongo1:27017", "<", "/scripts/init.js"]

    mongotester:
        build:
            context: ../MongoTester
            dockerfile: Dockerfile
        depends_on:
            - mongosetup
        volumes:
            - ../MongoTester/code:/code
            - ../data:/output
        environment:
            CONNECTION_CHAIN: mongodb://mongo1:27017,mongo2:27017,mongo3:27017,mongo4:27017,mongo5:27017/
            INTERATIONS: 10
            OUTPUT_FILENAME: "/output/replica-cluster-5.json"
